apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
spec:
  selector:
    matchLabels:
      app: employee-service
  replicas: 1
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
      - name: employee-service
        image: employee:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
