version: '2.1'
services:
    postgres:
        container_name: nokia-service.postgres
        build:
            context: .
            dockerfile: Postgres.Dockerfile
        ports:
            - 5434:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - shared-network
networks:
    shared-network:
          name: shared-network
